# Generated by Django 5.2.9 on 2025-12-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_state_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_structure',
            field=models.CharField(default='2_classes_700', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tai_certification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
