# Generated by Django 5.2.9 on 2025-12-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_fee_structure_student_instructor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belttest',
            name='tested_for_belt',
            field=models.CharField(choices=[('white', 'White'), ('yellow_stripe', 'Yellow Stripe'), ('yellow', 'Yellow'), ('green_stripe', 'Green Stripe'), ('green', 'Green'), ('blue_stripe', 'Blue Stripe'), ('blue', 'Blue'), ('red_stripe', 'Red Stripe'), ('red', 'Red'), ('red_black', 'Red Black'), ('black_1st_dan', 'Black 1st Dan'), ('black_2nd_dan', 'Black 2nd Dan'), ('black_3rd_dan', 'Black 3rd Dan'), ('black_4th_dan', 'Black 4th Dan'), ('black_5th_dan', 'Black 5th Dan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_belt',
            field=models.CharField(choices=[('white', 'White'), ('yellow_stripe', 'Yellow Stripe'), ('yellow', 'Yellow'), ('green_stripe', 'Green Stripe'), ('green', 'Green'), ('blue_stripe', 'Blue Stripe'), ('blue', 'Blue'), ('red_stripe', 'Red Stripe'), ('red', 'Red'), ('red_black', 'Red Black'), ('black_1st_dan', 'Black 1st Dan'), ('black_2nd_dan', 'Black 2nd Dan'), ('black_3rd_dan', 'Black 3rd Dan'), ('black_4th_dan', 'Black 4th Dan'), ('black_5th_dan', 'Black 5th Dan')], default='white', max_length=20),
        ),
    ]
