# Generated by Django 5.1 on 2025-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_belttest_tested_for_belt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyfee',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='payment_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', max_length=20),
        ),
    ]
