# Generated by Django 5.1 on 2025-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_monthlyfee_options_monthlyfee_payment_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='belttest',
            options={'ordering': ['-test_date']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='belttest',
            name='test_fee',
        ),
        migrations.RemoveField(
            model_name='belttest',
            name='tested_for_belt',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='belttest',
            name='certification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='belttest',
            name='new_belt',
            field=models.CharField(choices=[('white', 'White'), ('yellow_stripe', 'Yellow Stripe'), ('yellow', 'Yellow'), ('green_stripe', 'Green Stripe'), ('green', 'Green'), ('blue_stripe', 'Blue Stripe'), ('blue', 'Blue'), ('red_stripe', 'Red Stripe'), ('red', 'Red'), ('red_black', 'Red Black'), ('black_1st_dan', 'Black 1st Dan'), ('black_2nd_dan', 'Black 2nd Dan'), ('black_3rd_dan', 'Black 3rd Dan'), ('black_4th_dan', 'Black 4th Dan'), ('black_5th_dan', 'Black 5th Dan')], default='yellow_stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='belttest',
            name='previous_belt',
            field=models.CharField(choices=[('white', 'White'), ('yellow_stripe', 'Yellow Stripe'), ('yellow', 'Yellow'), ('green_stripe', 'Green Stripe'), ('green', 'Green'), ('blue_stripe', 'Blue Stripe'), ('blue', 'Blue'), ('red_stripe', 'Red Stripe'), ('red', 'Red'), ('red_black', 'Red Black'), ('black_1st_dan', 'Black 1st Dan'), ('black_2nd_dan', 'Black 2nd Dan'), ('black_3rd_dan', 'Black 3rd Dan'), ('black_4th_dan', 'Black 4th Dan'), ('black_5th_dan', 'Black 5th Dan')], default='white', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10),
        ),
    ]
