# Generated by Django 5.2.9 on 2025-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_attendance_options_alter_belttest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='belttest',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='belttest',
            name='certification_number',
        ),
        migrations.RemoveField(
            model_name='belttest',
            name='new_belt',
        ),
        migrations.RemoveField(
            model_name='belttest',
            name='previous_belt',
        ),
        migrations.AddField(
            model_name='belttest',
            name='test_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='belttest',
            name='tested_for_belt',
            field=models.CharField(choices=[('white', 'White'), ('yellow_stripe', 'Yellow Stripe'), ('yellow', 'Yellow'), ('green_stripe', 'Green Stripe'), ('green', 'Green'), ('blue_stripe', 'Blue Stripe'), ('blue', 'Blue'), ('red_stripe', 'Red Stripe'), ('red', 'Red'), ('red_black', 'Red Black'), ('black_1st_dan', 'Black 1st Dan'), ('black_2nd_dan', 'Black 2nd Dan'), ('black_3rd_dan', 'Black 3rd Dan'), ('black_4th_dan', 'Black 4th Dan'), ('black_5th_dan', 'Black 5th Dan')], default='white', max_length=20),
        ),
    ]
