# Generated by Django 5.2.9 on 2025-12-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_attendance_options_alter_belttest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='belttest',
            name='certification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
