# Generated by Django 5.2.9 on 2025-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_belttest_certification_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belttest',
            name='certification_number',
        ),
        migrations.AddField(
            model_name='belttest',
            name='certification_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
