# Generated by Django 5.2.9 on 2025-12-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_belttest_certification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='belttest',
            name='examiner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
