# Generated by Django 5.1 on 2025-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_student_admission_fee_student_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevent',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
    ]
