# Generated by Django 5.2.9 on 2025-12-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_studentevent_result_studentevent_event_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash')], max_length=10, null=True),
        ),
    ]
